/**
 * Stable, machine-readable error codes. The client switches on these;
 * human-readable messages may change freely.
 */
export const ErrorCodes = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  CONFLICT: 'CONFLICT',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  OTP_REQUIRED: 'OTP_REQUIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_RESEND_COOLDOWN: 'OTP_RESEND_COOLDOWN',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  /** A code issued for one purpose was presented to complete another. */
  OTP_WRONG_PURPOSE: 'OTP_WRONG_PURPOSE',
  REGISTRATION_NOT_FOUND: 'REGISTRATION_NOT_FOUND',
  REGISTRATION_EMAIL_NOT_VERIFIED: 'REGISTRATION_EMAIL_NOT_VERIFIED',
  REGISTRATION_ALREADY_DECIDED: 'REGISTRATION_ALREADY_DECIDED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  CSRF_INVALID: 'CSRF_INVALID',

  // Task / workflow
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ALREADY_CLAIMED: 'TASK_ALREADY_CLAIMED',
  TASK_NOT_CLAIMABLE: 'TASK_NOT_CLAIMABLE',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  TASK_NOT_OWNED: 'TASK_NOT_OWNED',
  TASK_EXPIRED: 'TASK_EXPIRED',
  LOCK_ACQUISITION_FAILED: 'LOCK_ACQUISITION_FAILED',

  // Collateral / limits
  INSUFFICIENT_AVAILABLE_LIMIT: 'INSUFFICIENT_AVAILABLE_LIMIT',
  CAPTAIN_DAILY_LIMIT_EXCEEDED: 'CAPTAIN_DAILY_LIMIT_EXCEEDED',
  CAPTAIN_MONTHLY_LIMIT_EXCEEDED: 'CAPTAIN_MONTHLY_LIMIT_EXCEEDED',
  PARTY_DAILY_LIMIT_EXCEEDED: 'PARTY_DAILY_LIMIT_EXCEEDED',
  PARTY_MONTHLY_LIMIT_EXCEEDED: 'PARTY_MONTHLY_LIMIT_EXCEEDED',
  AMOUNT_BELOW_MINIMUM: 'AMOUNT_BELOW_MINIMUM',
  AMOUNT_ABOVE_MAXIMUM: 'AMOUNT_ABOVE_MAXIMUM',
  CAPTAIN_OFFLINE: 'CAPTAIN_OFFLINE',
  CAPTAIN_SUSPENDED: 'CAPTAIN_SUSPENDED',

  // Proof / payout
  PROOF_REQUIRED: 'PROOF_REQUIRED',
  PROOF_ALREADY_SUBMITTED: 'PROOF_ALREADY_SUBMITTED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  PAYOUT_NOT_EXECUTED: 'PAYOUT_NOT_EXECUTED',
  PAYOUT_ALREADY_EXECUTED: 'PAYOUT_ALREADY_EXECUTED',
  PAYOUT_FAILED: 'PAYOUT_FAILED',
  REFERENCE_MISMATCH: 'REFERENCE_MISMATCH',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Notifications
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Audit
  REJECTION_REASON_REQUIRED: 'REJECTION_REASON_REQUIRED',
  NOT_PENDING_AUDIT: 'NOT_PENDING_AUDIT',

  // Import
  CSV_PARSE_ERROR: 'CSV_PARSE_ERROR',
  CSV_EMPTY: 'CSV_EMPTY',
  DUPLICATE_EXTERNAL_REF: 'DUPLICATE_EXTERNAL_REF',
  IMPORT_BATCH_NOT_FOUND: 'IMPORT_BATCH_NOT_FOUND',

  // Config
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_INVALID_VALUE: 'CONFIG_INVALID_VALUE',

  // Withdrawal ("Pay In")
  WITHDRAWAL_NOT_FOUND: 'WITHDRAWAL_NOT_FOUND',
  WITHDRAWAL_ALREADY_DECIDED: 'WITHDRAWAL_ALREADY_DECIDED',
  WITHDRAWAL_REQUEST_PENDING: 'WITHDRAWAL_REQUEST_PENDING',
  INSUFFICIENT_AVAILABLE_BALANCE: 'INSUFFICIENT_AVAILABLE_BALANCE',

  // DMC ledger
  INSUFFICIENT_DMC_BALANCE: 'INSUFFICIENT_DMC_BALANCE',
  INSUFFICIENT_PLATFORM_BALANCE: 'INSUFFICIENT_PLATFORM_BALANCE',
  CAPTAIN_NOT_FOUND: 'CAPTAIN_NOT_FOUND',
  INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
  REDEMPTION_NOT_FOUND: 'REDEMPTION_NOT_FOUND',
  REDEMPTION_ALREADY_DECIDED: 'REDEMPTION_ALREADY_DECIDED',
  PARTY_NOT_FOUND: 'PARTY_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  NO_CAPTAIN_AVAILABLE: 'NO_CAPTAIN_AVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
