import crypto from 'node:crypto';
import type { PayoutMethodType } from '../types';

/**
 * Human-facing task identifier: TASK-<partyCode>-<year>-<6-digit sequence>.
 * The sequence comes from a single atomic counter shared across every party,
 * so it is already globally unique on its own; the party code is prefixed
 * purely so the task's owner is legible at a glance across a mixed list.
 */
export function formatTaskCode(partyCode: string, year: number, sequence: number): string {
  return `TASK-${partyCode}-${year}-${sequence.toString().padStart(6, '0')}`;
}

/** Excludes the characters people misread aloud: 0/O and 1/I/L. */
const TRACKING_REF_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

/**
 * The same task as a captain sees it.
 *
 * `formatTaskCode` above deliberately spells out the owning party, which is
 * exactly what a captain must not learn — the rest of the system withholds the
 * party's name, code and tracking reference, and an identifier reading
 * TASK-PARTY-003-... would hand it back on every screen. So a captain is shown
 * this instead: unrelated to the party, unrelated to the sequence, and
 * therefore useless for counting a party's volume or grouping work by client.
 *
 * Still meant to be read aloud and typed, so it shares the tracking
 * reference's alphabet, which drops the four characters that get confused most
 * on a screen: 0 and O, 1 and I.
 */
export function generateCaptainTaskCode(): string {
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += TRACKING_REF_ALPHABET[crypto.randomInt(0, TRACKING_REF_ALPHABET.length)];
  }
  return `JOB-${code}`;
}

export function formatBatchCode(year: number, sequence: number): string {
  return `BATCH-${year}-${sequence.toString().padStart(5, '0')}`;
}

export function formatPartyCode(sequence: number): string {
  return `PARTY-${sequence.toString().padStart(3, '0')}`;
}

/**
 * A captain's code, from the same kind of atomic counter every other code here
 * uses.
 *
 * Worth spelling out why this exists: the seed used to write `CAP-001` as a
 * literal and no counter for captains existed anywhere, which was harmless only
 * while captains could not be created at runtime. The moment registration could
 * make a second one, the literal and a counter starting at 1 would both produce
 * `CAP-001` and collide on a unique index. So the seed draws from this counter
 * too, and the number a captain gets is simply the next one nobody has taken.
 */
export function formatCaptainCode(sequence: number): string {
  return `CAP-${sequence.toString().padStart(3, '0')}`;
}

/** Cryptographically random 6-digit OTP, uniformly distributed. */
export function generateOtp(): string {
  // rejection sampling avoids the modulo bias of (randomInt % 1000000)
  return crypto.randomInt(0, 1_000_000).toString().padStart(6, '0');
}

export function randomToken(bytes = 32): string {
  return crypto.randomBytes(bytes).toString('hex');
}

/**
 * Customer-facing tracking reference. Generated by the system at task
 * creation, never chosen by the party — this is what the party relays to
 * their (fictional) customer for use on the public tracking page. The
 * alphabet excludes visually ambiguous characters (0/O, 1/I/L) since a human
 * will be reading this off a screen and typing it elsewhere.
 */
export function generateTrackingRef(): string {
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += TRACKING_REF_ALPHABET[crypto.randomInt(0, TRACKING_REF_ALPHABET.length)];
  }
  return `DEMO-REF-${code}`;
}

/**
 * The legacy `identifier` field ("destination handle") is kept for search and
 * Customer dedup, but for a task created with a structured payout method it
 * is no longer typed by the party — it is derived from whichever method they
 * chose, so it still reads as a short, identifier-shaped label.
 */
export function deriveTaskIdentifier(payoutMethod: {
  type: PayoutMethodType;
  accountNumber?: string | null;
  upiId?: string | null;
  walletAddress?: string | null;
}): string {
  switch (payoutMethod.type) {
    case 'BANK':
      return `DEMO-BANK-${(payoutMethod.accountNumber ?? '').slice(-4)}`;
    case 'UPI':
      return payoutMethod.upiId ?? 'DEMO-UPI-UNKNOWN';
    case 'USDT':
      return `DEMO-USDT-${(payoutMethod.walletAddress ?? '').slice(-6).toUpperCase()}`;
  }
}

/** Constant-time string comparison, for OTP and CSRF token checks. */
export function timingSafeEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');
  if (bufA.length !== bufB.length) return false;
  return crypto.timingSafeEqual(bufA, bufB);
}

export function sha256(value: string): string {
  return crypto.createHash('sha256').update(value).digest('hex');
}
